name: fawad5_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  google_sign_in: ^5.0.7
  flutter_login_facebook: ^1.6.2
  flutter_switch: ^0.3.2
  flutter_staggered_grid_view: ^0.4.1
  intl: ^0.17.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Sora
      fonts: 
        - asset: assets/fonts/SoraSemiBold.ttf
          weight: 600
        - asset: assets/fonts/SoraLight.ttf
          weight: 300
        - asset: assets/fonts/SoraBold.ttf
          weight: 700
        - asset: assets/fonts/SoraRegular.ttf
          weight: 400
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextSemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProTextMedium.ttf
          weight: 500
